Added person student and teacher classes
Dagic-zewdu/school-library pull request #1
Opened 2022-05-10 08:11 UTC by Dagic-zewdu

In this pull request
  - Added student class based on the design.
  - Added person class based on the ddesign.
  - Added teacher class based on the design.

2022-05-10 15:30 UTC, FrederickMih requested changes
Hi @Dagic-zewdu , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/WOTMeqMcNkLuXibbKz/giphy.gif)

# To Highlights

:fast_forward: GitHub workflow has been followed :heavy_check_mark: 
:fast_forward: Linters has been correctly setup and all checks passed :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-10 15:30 UTC, FrederickMih commented on person.rb
> +  attr_reader :rentals, :name, :id, :age, :parent_permission
- [ ] Hi @Dagic-zewdu, please don't forget that we should be able to write and modify the `name` and `age` of the person hence we should either create setters for `name` and `age` again or at once go with `attr_accessor `for name and age.

```ruby
  attr_accessor :name, :age 
  # *:id should only be able to be retrieved so only the Getter is defined
  attr_reader :id 
```

- [Helpful resource](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_principles_examples.md#useful-shortcuts-attr_reader-attr_writer-and-attr_accessor)

2022-05-10 15:30 UTC, FrederickMih commented on person.rb
> +  end
- [Optional] After defining the `initialize `object constructor method, I don't think it's necessary to do this again. What did you think?

2022-05-10 15:30 UTC, FrederickMih commented on person.rb
> +    of_age? || @parent_permission == true
- **Summary**: If a person is of age or has obtained permission from the parent then he/she can use services.

- [Optional] You have defaulted the value of `@parent_permission` to be true in the constructor(`@parent_permission == true`) hence there's no need to assign true to @parent_permission again. What did you think?

2022-05-10 15:30 UTC, FrederickMih commented on student.rb
> +  attr_reader :classroom, :name, :id, :age, :parent_permission
- [ ] As already stated above :point_up: , the name and age can be equally modified. Refer to the comment above. Again you are already making use of inheritance hence this may not be necessary again. What did you think?. The only new property that you have added to this class is the `classroom`. 

- [Helpful resource](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/class_and_object_for_irb.md#constructor-and-instance-vars)

2022-05-10 15:30 UTC, FrederickMih commented on teacher.rb
> +  attr_reader :name, :id, :age, :specialization, :parent_permission
- [ ] Nice job for making use of the inheritance principle here :+1:  . As already pointed out above, the only new property that has been added here is specialization.  Calling the super() method inside the constructor and passing in these properties is enough. This principle prevents you from doing the same job over and over.

2022-05-10 15:30 UTC, FrederickMih commented on README.md
>  👤 **Dagic-zewdu**
- [ ] Please let's make use of all these headers from [this Microverse README template](https://github.com/microverseinc/readme-template). Add more details in the Getting Started section(how to setup up the project locally). The License section of the Microverse README template is also missing. By adding all these details and headers, our README file will become descriptive and professional.

2022-05-11 11:27 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED 🍾✔🎉**
Hello @Dagic-zewdu 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-11 11:41 UTC, merged