Try to implement associations
Dagic-zewdu/school-library pull request #3
Opened 2022-05-11 15:13 UTC by Dagic-zewdu

In this milestone of the school-library project
   - Create a class Classroom and give it a has-many relationship with students.
   - Create Book and Rental classes. Then add a many-to-many relationship between book and person using the Rental intermediate class.

2022-05-11 17:49 UTC, Lameck1 requested changes
Hi, @Dagic-zewdu, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### Highlights
- Professional README ✔️
- Clean code ✔️ 
- Good commit messages ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, remember to tag me in your question so I can receive the notification.**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-11 17:49 UTC, Lameck1 commented on rental.rb
> +  end
- [x] These methods are really not necessary. They are just repeating whatever is taking place in the initialize block. Please delete these two methods.

2022-05-11 17:49 UTC, Lameck1 commented on rental.rb
> +    @person.rentals.push(self) unless @person.rentals.include?(self)
- [x] The requirement states 👇🏼:
  
  > - Create the has-many side of Person and Rental (a person has many rentals).
  
  If a person should have many rentals, then this block `unless @person.rentals.include?(self)` negates this. Your implementation restricts a person to have only one rental. Please remove the unless block.

2022-05-11 17:49 UTC, Lameck1 commented on rental.rb
> +    @book.rentals.push(self) unless @book.rentals.include?(self)
- [x] Same issues as above for book. Please remove the unless block.

2022-05-11 17:49 UTC, Lameck1 commented on person.rb
>    end
- [x] In the above review comments, we realize that the Rental class is already taking care of pushing rentals to either a person or a book (`@person.rentals.push(self)` and `@book.rentals.push(self)` respectively). Therefore, whatever this method is doing currently is another repetition that will be a bug when the app is run.

  What we should be doing here is defining how a rental should be created by using the Rental class. Consider the example below:
  
  ```ruby
  def add_rental(book, date)
    Rental.new(date, book, self)
  end
  ```

2022-05-11 17:49 UTC, Lameck1 commented on book.rb
> +  end
- [x] Same as above, please refactor this accordingly. Get some hint on how the above example for the Person class has been implemented.

2022-05-12 07:42 UTC, Meltrust approved these changes
Hi @Dagic-zewdu,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for refactoring the rental and person methods, as requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-12 07:42 UTC, Meltrust commented on rental.rb
> +    @book.rentals.push(self)
- [ ] OPTIONAL: Helpful tip:  Easier way to call the #push method in Ruby:

```ruby
@person = person
person.rentals << self

@book = book
book.rentals << self

2022-05-12 10:05 UTC, merged